name: Apps Home

on:
  push:
    branches:
      - main

jobs:
  apps-home:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install modules
        run: yarn

      - name: Build
        run: yarn pdf
